image: rocker/hadleyverse
script:
  curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  chmod 755 ./travis-tool.sh
  ./travis-tool.sh install_deps
  ./travis-tool.sh run_tests
